# IntelliJ Platform Artifacts Repositories
# -> https://www.jetbrains.org/intellij/sdk/docs/reference_guide/intellij_artifacts.html

pluginGroup = org.nemwiz
pluginName = jira-commit-message
pluginRepositoryUrl = https://github.com/toshaTikhonov/jira-commit-message-intellij-plugin
pluginVersion = 4.0.0-svn

pluginSinceBuild = 233
pluginUntilBuild =

platformType = IC
platformVersion = 2023.3.7

gradleVersion = 8.9

# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
platformPlugins =
# CLion/IntelliJ bundled Subversion integration.
platformBundledPlugins = Subversion

kotlin.stdlib.default.dependency = false

org.gradle.configuration-cache = true
org.gradle.caching = true
